CREATE TABLE IF NOT EXISTS papel (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
    id BIGSERIAL PRIMARY KEY,
    login VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(100) NOT NULL,
    papel_id BIGINT NOT NULL,
    FOREIGN KEY (papel_id) REFERENCES papel(id)
);
